---
- hosts: "redmine"
  become: yes
  pre_tasks:
  - name: Redmine. Install packages
    apt:
      name: "{{ apt_redmine_packages }}"
      state: latest
      update_cache: yes
  roles: 
    - mysql
    - redmine    
  tasks:
  - name: Configuration files for virtualhost
    template:
      src: templates/redmine.site.conf.j2
      dest: "/etc/apache2/sites-enabled/redmine.site.conf"
    notify:
      - apache restart
  - name: "Add {{ app_fqdn }} to host file"
    shell: echo "127.0.0.1       {{ app_fqdn }}" >> /etc/hosts
    tags:
      - test
  - uri:
      url: "http://{{ app_fqdn }}"
      return_content: yes
    register: this
    failed_when: "'Jean-Philippe Lang' not in this.content"
    tags:
      - test
  - lineinfile:
      path: /etc/hosts
      state: absent
      regexp: '^127.0.0.1       {{ app_fqdn }}'
    tags:
      - test
      - always


  handlers:
     - name: apache restart
       service:
         name: apache2
         state: restarted      
   

